# Site settings
site: Paiva
title: Paiva
keywords: blog
description: >-
  Paiva's blog
lang: en-US
timezone:  Europe/Lisbon
google_verify:      XXX # Put your Google Verification here
google_analytics:   G-S2PWD1M7MK
discus-identifier:  XXX

# Author settings
author:
  name: David Paiva
  bio: Sofware Developer @ BRAVANTIC <br> Software Development Student @ ISTEC
  picture: assets/images/profile.jpg 
  github: jaxxibae # github username
  twitter: jaxxibae # twitter username
  instagram: jaxxibae # instagram username
  linkedin: dpaiva0 # linkedin username
  email: hi@paiva.codes # email adress


# URL settings
url: "https://dpaiv0.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false